package com.lab.opengarage.ui.theme

import androidx.compose.ui.graphics.Color

// OpenGarage 브랜드: 브리티시 레이싱 그린 + 크림/골드 — 클래식카 개러지 무드 (Material 3)

// Light
val md_primary = Color(0xFF1E6642)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFA8F2C4)
val md_onPrimaryContainer = Color(0xFF00210F)
val md_secondary = Color(0xFF4E6355)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFD0E8D6)
val md_onSecondaryContainer = Color(0xFF0B1F13)
val md_tertiary = Color(0xFF7A5F00)
val md_onTertiary = Color(0xFFFFFFFF)
val md_tertiaryContainer = Color(0xFFF6E1A7)
val md_onTertiaryContainer = Color(0xFF251A00)
val md_background = Color(0xFFFAF7EC)
val md_onBackground = Color(0xFF1A1C18)
val md_surface = Color(0xFFFAF7EC)
val md_onSurface = Color(0xFF1A1C18)
val md_surfaceVariant = Color(0xFFDDE5DB)
val md_onSurfaceVariant = Color(0xFF414941)
val md_surfaceContainer = Color(0xFFEFF1E4)
val md_outline = Color(0xFF717970)
val md_outlineVariant = Color(0xFFC1C9BF)

// Dark
val md_primary_d = Color(0xFF8CD5A8)
val md_onPrimary_d = Color(0xFF00391D)
val md_primaryContainer_d = Color(0xFF0A4D2C)
val md_onPrimaryContainer_d = Color(0xFFA8F2C4)
val md_secondary_d = Color(0xFFB5CCBB)
val md_onSecondary_d = Color(0xFF21352A)
val md_secondaryContainer_d = Color(0xFF374B3E)
val md_onSecondaryContainer_d = Color(0xFFD0E8D6)
val md_tertiary_d = Color(0xFFE8C55B)
val md_onTertiary_d = Color(0xFF3B2F00)
val md_tertiaryContainer_d = Color(0xFF554500)
val md_onTertiaryContainer_d = Color(0xFFF6E1A7)
val md_background_d = Color(0xFF0F1410)
val md_onBackground_d = Color(0xFFE0E4DB)
val md_surface_d = Color(0xFF0F1410)
val md_onSurface_d = Color(0xFFE0E4DB)
val md_surfaceVariant_d = Color(0xFF414941)
val md_onSurfaceVariant_d = Color(0xFFC1C9BF)
val md_surfaceContainer_d = Color(0xFF1A201B)
val md_outline_d = Color(0xFF8B938A)
val md_outlineVariant_d = Color(0xFF414941)
