package com.lab.opengarage.ui.theme

import androidx.compose.ui.graphics.Color

// OpenGarage 브랜드: 번트 오렌지(엠버) + 따뜻한 차콜 — 클래식카 개러지 무드 (Material 3)

// Light
val md_primary = Color(0xFFA63A1E)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFFFDBCF)
val md_onPrimaryContainer = Color(0xFF3A0B00)
val md_secondary = Color(0xFF77574E)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFFFDBCF)
val md_onSecondaryContainer = Color(0xFF2C150E)
val md_tertiary = Color(0xFF6C5D2F)
val md_onTertiary = Color(0xFFFFFFFF)
val md_tertiaryContainer = Color(0xFFF6E1A7)
val md_onTertiaryContainer = Color(0xFF221B00)
val md_background = Color(0xFFFFF8F6)
val md_onBackground = Color(0xFF231917)
val md_surface = Color(0xFFFFF8F6)
val md_onSurface = Color(0xFF231917)
val md_surfaceVariant = Color(0xFFF5DED7)
val md_onSurfaceVariant = Color(0xFF53433F)
val md_surfaceContainer = Color(0xFFFCEAE4)
val md_outline = Color(0xFF85736E)
val md_outlineVariant = Color(0xFFD8C2BB)

// Dark
val md_primary_d = Color(0xFFFFB59C)
val md_onPrimary_d = Color(0xFF5D1900)
val md_primaryContainer_d = Color(0xFF822405)
val md_onPrimaryContainer_d = Color(0xFFFFDBCF)
val md_secondary_d = Color(0xFFE7BDB1)
val md_onSecondary_d = Color(0xFF442A21)
val md_secondaryContainer_d = Color(0xFF5D4036)
val md_onSecondaryContainer_d = Color(0xFFFFDBCF)
val md_tertiary_d = Color(0xFFD9C58D)
val md_onTertiary_d = Color(0xFF3A2F05)
val md_tertiaryContainer_d = Color(0xFF52461A)
val md_onTertiaryContainer_d = Color(0xFFF6E1A7)
val md_background_d = Color(0xFF1A110F)
val md_onBackground_d = Color(0xFFF1DFD9)
val md_surface_d = Color(0xFF1A110F)
val md_onSurface_d = Color(0xFFF1DFD9)
val md_surfaceVariant_d = Color(0xFF53433F)
val md_onSurfaceVariant_d = Color(0xFFD8C2BB)
val md_surfaceContainer_d = Color(0xFF271D1A)
val md_outline_d = Color(0xFFA08C87)
val md_outlineVariant_d = Color(0xFF53433F)
